<?php

$lang['timezone'] = 'Zeitzone die zur Berechnung verwendet werden soll. <br> Bei keiner Angabe, wird die auf den Server festgelegte Zeitzone verwendet. Sie können eine der IDs aus der <a href="http://php.net/manual/en/timezones.php" target="_blank">"Liste der unterstützten Zeitzonen" im PHP-Handbuch </a> (Link öffnet in neuem Fenster) verwenden.';
$lang['excludeMgAndSp'] = 'Keine Manager und Administratoren zählen? (Siehe Konfiguration "<a href="#config___manager">manager</a>" und "<a href="#config___superuser">superuser</a>")';
$lang['exclusionList'] = 'IPs und Remote-Hosts, die ausgeschlossen werden. <br> Das Plugin zählt Benutzer mit diesen IPs und Remote-Hosts nicht. Diese Liste ist nützlich, wenn Ihre Website über viele Zugriffe von Bots von bestimmten IPs und Remote-Hosts verfügt. <br> Das Plugin erhält Remote-Hosts über IPs Reverse Lookup (gethostbyaddr). <br> Geben Sie einen ein IP oder Remote-Host pro Zeile. <br> Platzhalter verfügbar: <br>? = ein Zeichen (ein alphanumerisches Zeichen, ein Punkt "." oder ein Bindestrich "-") <br> * = ein oder mehrere Zeichen (alphanumerische Zeichen, Punkte "." oder Bindestriche "-") <br>! = ein Zeichen (eine Ziffer) <br> ~ = ein oder mehrere Zeichen (Ziffern) <br> <br> zB: "123.456.???.123" -> 123.456.789.123 usw. (123.456.78.123 würde nicht ausgeschlossen werden) <br> zB: "* .example.com" -> 123.456.789.123.example.com, 1-2-3-4.rooter.example.com usw. ';
$lang['reverseLookupFailed'] = 'Vom Zähler ausschließen, wenn die Rückwärtssuche (IPs zu Remote-Hosts) fehlgeschlagen ist (IPs von Robotern neigen dazu, die Rückwärtssuche abzulehnen).';
$lang['reverseLookupException'] = 'IPs, die das Plugin nicht auf die Option "reverseLookupFailed" anwendet <br> Geben Sie eine IP pro Zeile ein. <br> Platzhalter verfügbar: <br>? = ein Zeichen <br> * = ein oder mehrere Zeichen <br> <br> zB: "123.456.???.123" -> 123.456.789.123 usw. (123.456.78.123 werden nicht ausgeschlossen) <br > zB: "123. *. 789.123" -> 123.456.789.123, 123.9.789.123 usw.';
$lang['reverseLookupCntrException'] = 'Länder, in denen das Plugin nicht die Option "reverseLookupFailed" anwenden soll. <br> Das Plugin erhält Ländercodes von dem DNS-Dienst "cc.wariate.jp" (<a href="http://cc.wariate.jp/" target="_blank">Details in Japanisch</a>). <br> Geben Sie zweistellige Ländercodes (ISO 3166-1 alpha-2) ein, mehrere bitte durch Komma getrennt.';
$lang['usrExclusion'] = 'Benutzer oder Benutzergruppen, die ausgeschlossen werden <br> Das Plugin zählt diese Benutzer und Benutzer in diesen Gruppen nicht. <br> Geben Sie Benutzer und Benutzergruppen durch Komma getrennt ein.';
$lang['cntrExclusion'] = 'Länder, die ausgeschlossen werden <br> Das Plugin zählt keine Benutzer aus diesen Ländern. Diese Liste ist nützlich, wenn Ihre Website über viele Zugriffe von Robotern aus bestimmten Ländern verfügt. <br> Das Plugin erhält Ländercodes von dem DNS-Dienst "cc.wariate.jp" (<a href="http://cc.wariate.jp/" target="_blank">Details in Japanisch</a>). <br> Geben Sie zweistellige Ländercodes (ISO 3166-1 alpha-2) ein, mehrere bitte durch Komma getrennt.';
$lang['cntrInclusion'] = 'Festlegen bestimmter zu zählender Länder. <br> Wenn Sie hier die Länder angeben, zählt das Plugin NUR Benutzer aus diesen Ländern.<br>Das Plugin erhält Ländercodes von dem DNS-Dienst "cc.wariate.jp" (<a href="http://cc.wariate.jp/" target="_blank">Details in Japanisch</a>). <br> Geben Sie zweistellige Ländercodes (ISO 3166-1 alpha-2) ein, mehrere bitte durch Komma getrennt.';
$lang['sfsExFreq'] = 'Das Plugin überprüft die IP-Adresse des Besuchers auf wiederholdende Zugriffe in kurzer Zeit, um Spammer nicht zu zählen. (Stopforumspam2-Plugin erforderlich) <br> "0" = deaktiviert <br>  "-1" prüfung mit Stopforumspam2-Plugin. <br> alle anderen Werte zwischen 1 und 100 werden als Grenzwert verwendet, ab denen die Zugriffe dieser IP nicht mehr erfasst werden.';
$lang['sfsExConf'] = 'Das Plugin überprüft die IP-Adresse des Besuchers auf wiederholdende Zugriffe in kurzer Zeit, um Spammer nicht zu zählen. (Stopforumspam2-Plugin erforderlich) <br> "0" = deaktiviert <br>  "-1" prüfung mit Stopforumspam2-Plugin. <br> alle anderen Werte zwischen 1 und 100 werden als Grenzwert verwendet, ab denen die Zugriffe dieser IP nicht mehr erfasst werden.';
$lang['saveLog'] = 'Speichern Sie das Protokoll der IPs, das Datum und die Uhrzeit, zu der Besucher auf dieses Wiki zugreifen? <br> Das Protokoll wird für jede Seite aufgezeichnet. Diese Option ist nützlich, wenn Sie entscheiden, welche IPs, Remote-Hosts und Länder vom Zähler ausgeschlossen werden sollen. <br> Die Protokolldateien werden im Verzeichnis <code>accscounterlog</code> in Ihrem Cache-Verzeichnis (innerhalb von <a href="#config___savedir">Datenverzeichnis</a> in der Standardkonfiguration) gespeichert. Erstellen Sie die Protokolldateien und löschen Sie diese regelmäßig, da der Umfang schnell sehr groß wird.';
$lang['excludeMgAndSp_o_0']  ='Beide Gruppen zählen';
$lang['excludeMgAndSp_o_sp']  ='Administratoren nicht mitzählen';
$lang['excludeMgAndSp_o_mg']    ='Manager und Administratoren nicht mitzählen.';
$lang['saveLog_o_0'] = 'nicht speichern';
$lang['saveLog_o_ppage'] = 'alles in einer Datei speichern';
$lang['saveLog_o_pdate'] = 'speichern, aber jeden Tag eine neue Datei';
$lang['ipgdpr'] = 'Sollen die IP-Adressen anonymisiert werden, um den Anforderungen der DSGVO gerecht zu werden?<br>Um die IP von Spammer oder BOTs zu erhalten, diese Funktion deaktivieren und im Anschluss wieder aktivieren, sowie die Logs vom Server löschen / bereinigen  mit einem FTP-Programm. Die Erkennung von BOTs und Spammern ist trotz aktivierter Funktion möglich.';
